import React, { useState } from 'react';
import NoteContext from './NoteContext';

const NoteState = (props) => {




    const [datas, setData] = useState([])
    const [userdata, setUserData] = useState("")

    const setdata = (data) => {
        setData(data);
        console.log("first")
    }

    // const productData1 = [
    //     {
    //         id: 1,
    //         products: "chennai super king jercey",
    //         thumbnail: "https://res.cloudinary.com/dbe8yf165/image/upload/v1685796157/cricify/ipl/csk-match-jersey-2023-dhoni-1599-back-front_am88y0.jpg",
    //         Men: "Yes",
    //         Women: "No",
    //         Ipl: "Yes",
    //         Wpl: "No",
    //         International: "No",
    //         Size: "One Size-Free Size",
    //         Category: "Jersey",
    //         Rating: 5,
    //         discountprice: 1602,
    //         mrp: 1790,



    //     },
    //     {
    //         id: 2,
    //         products: "Colcata night riders pass",
    //         thumbnail: "https://res.cloudinary.com/dbe8yf165/image/upload/v1685796121/cricify/fan-merchandise/Kolkata_Knight_Riders_-_Luggage_Bag_Tags_Pack_of_-_1_-231_ymfjeh.jpg",
    //         Men: "yes",
    //         Women: "yes",
    //         Ipl: "yes",
    //         Wpl: "No",
    //         International: "no",
    //         Size: "One Size-Free Size",
    //         Category: "merchandise",
    //         Rating: 3.3,
    //         discountprice: 208,
    //         mrp: 231,

    //     },
    //     {
    //         id: 3,
    //         products: "India 2003-06 jercey ",
    //         Men: "Yes",
    //         thumbnail: "https://res.cloudinary.com/dbe8yf165/image/upload/v1685866681/cricify/ind-2003-2006-jersey-1999_fbbma3.jpg",
    //         Men: "Yes",
    //         Women: "no",
    //         Ipl: "no",
    //         Wpl: "No",
    //         International: "yes",
    //         Size: "One Size-Free Size",
    //         Category: "Jersey",
    //         Rating: 4.1,
    //         discountprice: 1889,
    //         mrp: 2099,

    //     }
    //     , {
    //         id: 4,
    //         products: "India 2003-06 jercey ",
    //         Men: "yes",
    //         thumbnail: "https://res.cloudinary.com/dbe8yf165/image/upload/v1685796122/cricify/fan-merchandise/Sports_Gym_Bag_CSK-1699_pocypb.jpg",
    //         Men: "yes",
    //         Women: "yes",
    //         Ipl: "yes",
    //         Wpl: "No",
    //         International: "no",
    //         Size: "One Size-Free Size",
    //         Category: "merchandise",
    //         Rating: 4.1,
    //         discountprice: 1529,
    //         mrp: 1699,

    //     },
    //     {
    //         id: 5,
    //         products: "WOMEN BLUE WHITE MI - OFFICIAL SLIDER FLIP FLOPS ",
    //         thumbnail: "https://res.cloudinary.com/dbe8yf165/image/upload/v1685796122/cricify/fan-merchandise/Women_s_Blue_White_Mi-_Official_Slider_Flip_Flops-999_hpkbd8.jpg",
    //         Men: "no",
    //         Women: "yes",
    //         Ipl: "yes",
    //         Wpl: "yes",
    //         International: "no",
    //         Size: "One Size-Free Size",
    //         Category: "merchandise",
    //         Rating: 5,
    //         discountprice: 899,
    //         mrp: 999,
    //     },
    //     {
    //         id: 6,
    //         products: "WOMEN BLUE WHITE MI - OFFICIAL SLIDER FLIP FLOPS ",
    //         thumbnail: "https://res.cloudinary.com/dbe8yf165/image/upload/v1685796121/cricify/fan-merchandise/Chennai_Super_Kings_-_Yellove_Sipper-799_cmknc8.jpg",
    //         Men: "yes",
    //         Women: "yes",
    //         Ipl: "yes",
    //         Wpl: "no",
    //         International: "no",
    //         Size: "1 Litter",
    //         Category: "merchandise",
    //         Rating: 3.8,
    //         discountprice: 719,
    //         mrp: 999,
    //     },
    //     {
    //         id: 7,
    //         products: "sg Full cricket kit combo ",
    //         thumbnail: "https://res.cloudinary.com/dbe8yf165/image/upload/v1685796138/cricify/accessories/SG_Full_Cricket_Kit_Combo_awljtl.jpg",
    //         Men: "yes",
    //         Women: "yes",
    //         Ipl: "yes",
    //         Wpl: "no",
    //         International: "no",
    //         Size: "1 Litter",
    //         Category: "gears",
    //         Rating: 4.8,
    //         discountprice: 24499,
    //         mrp: 29999,
    //     },
    //     {
    //         id: 8,
    //         products: "royal challenge banglore (rcb) jercey ",
    //         thumbnail: "https://res.cloudinary.com/dbe8yf165/image/upload/v1685796160/cricify/ipl/rcb-match-jersey-2023-virat-1299-back-front_k19wao.jpg",
    //         Men: "yes",
    //         Women: "no",
    //         Ipl: "yes",
    //         Wpl: "no",
    //         International: "no",
    //         Size: "",
    //         Category: "gears",
    //         Rating: 4.8,
    //         discountprice: 1499,
    //         mrp: 1599,
    //     },
    //     {
    //         id: 9,
    //         products: "gujarat titan jerceys (gt training jacket)",
    //         thumbnail: "https://res.cloudinary.com/dbe8yf165/image/upload/v1685796121/cricify/fan-merchandise/GT-Training_Jacket-1799_rbbdcp.jpg",
    //         Men: "yes",
    //         Women: "yes",
    //         Ipl: "yes",
    //         Wpl: "no",
    //         International: "no",
    //         Size: "One Size-Free Size",
    //         Category: "Jersey",
    //         Rating: 4.8,
    //         discountprice: 1299,
    //         mrp: 1399,
    //     },
    //     {
    //         id: 10,
    //         products: "gujarat titan jerceys (gt training jacket)",
    //         thumbnail: "https://res.cloudinary.com/dbe8yf165/image/upload/v1685796122/cricify/fan-merchandise/LSG_The_Super_Giants_-_Square_Pillows-399_ur12ps.jpg",
    //         Men: "yes",
    //         Women: "yes",
    //         Ipl: "yes",
    //         Wpl: "no",
    //         International: "no",
    //         Size: "One Size-Free Size",
    //         Category: "merchandise",
    //         Rating: 4.8,
    //         discountprice: 299,
    //         mrp: 399,
    //     },
    //     {
    //         id: 11,
    //         products: "INDIA 2022-23 JERSEY",
    //         thumbnail: "https://res.cloudinary.com/dbe8yf165/image/upload/v1685866681/cricify/ind-jersey-22-23-front-back-2499_h3vpla.jpg",
    //         Men: "yes",
    //         Women: "no",
    //         Ipl: "no",
    //         Wpl: "no",
    //         International: "yes",
    //         Size: "One Size-Free Size",
    //         Category: "Jersey",
    //         Rating: 4.1,
    //         discountprice: 2199,
    //         mrp: 2499,
    //     },
    //     {
    //         id: 12,
    //         products: "MI-OFFICIAL NEW ERA 9FIFTY CAP-NAVY",
    //         thumbnail: "https://res.cloudinary.com/dbe8yf165/image/upload/v1685796122/cricify/fan-merchandise/MI-Official_New_Era_9Fifty_Cap-Navy-1699_lv6uac.jpg",
    //         Men: "yes",
    //         Women: "yes",
    //         Ipl: "yes",
    //         Wpl: "no",
    //         International: "no",
    //         Size: "One Size-Free Size",
    //         Category: "merchandise",
    //         Rating: 4.1,
    //         discountprice: 2199,
    //         mrp: 2499,
    //     },
    //     {
    //         id: 13,
    //         products: "INDIA 1985 FAN JERSEY",
    //         thumbnail: "https://res.cloudinary.com/dbe8yf165/image/upload/v1685866681/cricify/ind-1985-fan-jersey-1399_fbtvlz.png",
    //         Men: "yes",
    //         Women: "no",
    //         Ipl: "no",
    //         Wpl: "no",
    //         International: "yes",
    //         Size: "One Size-Free Size",
    //         Category: "Jersey",
    //         Rating: 3.1,
    //         discountprice: 1259,
    //         mrp: 1399,
    //     },
    //     {
    //         id: 14,
    //         products: "SS Ton Reserve Edition English Willow Short Handle Cricket BatSS Ton Reserve Edition English Willow Short Handle Cricket Bat",
    //         thumbnail: "https://res.cloudinary.com/dbe8yf165/image/upload/v1685940029/cricify/accessories/SS_Ton_Reserve_Edition_English_Willow_Short_Handle_Cricket_Bat-39999_kb0hwe.jpg",
    //         Men: "yes",
    //         Women: "yes",
    //         Ipl: "yes",
    //         Wpl: "yes",
    //         International: "yes",
    //         Size: "One Size-Free Size",
    //         Category: "Gears",
    //         Rating: 4.8,
    //         discountprice: 35999,
    //         mrp: 39999,
    //     },
    //     {
    //         id: 15,
    //         products: "INDIA 2007 T20 WC JERSEY",
    //         thumbnail: "https://res.cloudinary.com/dbe8yf165/image/upload/v1685866680/cricify/ind-2007-t20-wc-jersey-2099_aowuv3.jpg",
    //         Men: "yes",
    //         Women: "no",
    //         Ipl: "no",
    //         Wpl: "no",
    //         International: "yes",
    //         Size: "One Size-Free Size",
    //         Category: "Jersey",
    //         Rating: 4.9,
    //         discountprice: 3599,
    //         mrp: 4999,
    //     },
    //     {
    //         id: 16,
    //         products: "DSC CONDOR ATMOS LEATHER CRICKET BATTING GLOVES",
    //         thumbnail: "https://res.cloudinary.com/dbe8yf165/image/upload/v1685796136/cricify/accessories/DSC_Condor_Atmos_Leather_Cricket_Batting_Gloves-910_ighvtk.jpg",
    //         Men: "yes",
    //         Women: "yes",
    //         Ipl: "yes",
    //         Wpl: "yes",
    //         International: "yes",
    //         Size: "One Size-Free Size",
    //         Category: "Gears",
    //         Rating: "1.9",
    //         discountprice: 259,
    //         mrp: 459,
    //     },
    //     {
    //         id: 17,
    //         products: "INDIA 2011 WC JERSEY",
    //         thumbnail: "https://res.cloudinary.com/dbe8yf165/image/upload/v1685866680/cricify/ind-2011-wc-jersey-3999_uvi2gc.jpg",
    //         Men: "yes",
    //         Women: "no",
    //         Ipl: "no",
    //         Wpl: "no",
    //         International: "yes",
    //         Size: "One Size-Free Size",
    //         Category: "Jersey",
    //         Rating: 5,
    //         discountprice: 259,
    //         mrp: 459,
    //     }, {
    //         id: 18,
    //         products: "LSG GAZAB ANDAZ - FRIDGE MAGNETS",
    //         thumbnail: "https://res.cloudinary.com/dbe8yf165/image/upload/v1685796122/cricify/fan-merchandise/LSG_Gazab_Andaz_-_Fridge_Magnets-199_k2ef0r.jpg",
    //         Men: "yes",
    //         Women: "yes",
    //         Ipl: "yes",
    //         Wpl: "no",
    //         International: "no",
    //         Size: "One Size-Free Size",
    //         Category: "Merchandise",
    //         Rating: "1.9",
    //         discountprice: 179,
    //         mrp: 299,
    //     }, {
    //         id: 19,
    //         products: "RAJASTHAN ROYALS(RR) JERSEY",
    //         thumbnail: "https://res.cloudinary.com/dbe8yf165/image/upload/v1685796160/cricify/ipl/rr-match-jersey-2023-sanju-1092-back-front_lxx2gp.jpg",
    //         Men: "yes",
    //         Women: "yes",
    //         Ipl: "yes",
    //         Wpl: "yes",
    //         International: "no",
    //         Size: "One Size-Free Size",
    //         Category: "Merchandise",
    //         Rating: "1.9",
    //         discountprice: 999,
    //         mrp: 1999,
    //     }, {
    //         id: 20,
    //         products: "ICC T20 BLACK BACKPACK",
    //         thumbnail: "https://res.cloudinary.com/dbe8yf165/image/upload/v1685796121/cricify/fan-merchandise/icc-t20-black-backpack-715_ki5orc.jpg",
    //         Men: "yes",
    //         Women: "yes",
    //         Ipl: "no",
    //         Wpl: "no",
    //         International: "yes",
    //         Size: "One Size-Free Size",
    //         Category: "Merchandise",
    //         Rating: "3.9",
    //         discountprice: 644,
    //         mrp: 799,
    //     }, {
    //         id: 21,
    //         products: "INDIA BLUE BLACK STRING BAG",
    //         thumbnail: "https://res.cloudinary.com/dbe8yf165/image/upload/v1685796121/cricify/fan-merchandise/india-unisex-blue-black-string-bag-379_v4h21n.jpg",
    //         Men: "yes",
    //         Women: "yes",
    //         Ipl: "yes",
    //         Wpl: "yes",
    //         International: "yes",
    //         Size: "One Size-Free Size",
    //         Category: "Merchandise",
    //         Rating: "4.2",
    //         discountprice: 299,
    //         mrp: 499,
    //     }, {
    //         id: 22,
    //         products: "SUNRISERS HYDERABAD(SRH) JERSEY",
    //         thumbnail: "https://res.cloudinary.com/dbe8yf165/image/upload/v1685796161/cricify/ipl/srh-match-jersey-2023-599-back-front_nymjz3.jpg",
    //         Men: "yes",
    //         Women: "yes",
    //         Ipl: "yes",
    //         Wpl: "no",
    //         International: "no",
    //         Size: "One Size-Free Size",
    //         Category: "Jersey",
    //         Rating: "1.9",
    //         discountprice: 539,
    //         mrp: 599,
    //     }, {
    //         id: 23,
    //         products: "PUNJAB KINGS(PK) JERSEY",
    //         thumbnail: "https://res.cloudinary.com/dbe8yf165/image/upload/v1685796160/cricify/ipl/punjab-match-jersey-2023-zinta-799-back-front_ckph5r.jpg",
    //         Men: "yes",
    //         Women: "yes",
    //         Ipl: "yes",
    //         Wpl: "no",
    //         International: "no",
    //         Size: "One Size-Free Size",
    //         Category: "Jersey",
    //         Rating: "1.9",
    //         discountprice: 1184,
    //         mrp: 1316,
    //     }, {
    //         id: 24,
    //         products: "SUNRISERS HYDERABAD - ACRYLIC KEYCHAINS PACK OF - 2",
    //         thumbnail: "https://res.cloudinary.com/dbe8yf165/image/upload/v1685796121/cricify/fan-merchandise/Sunrisers_Hyderabad_-_Acrylic_Keychains_Pack_of_-_2_-182_wvz5tk.jpg",
    //         Men: "yes",
    //         Women: "yes",
    //         Ipl: "yes",
    //         Wpl: "no",
    //         International: "no",
    //         Size: "One Size-Free Size",
    //         Category: "Gears    ",
    //         Rating: "1.9",
    //         discountprice: 259,
    //         mrp: 459,
    //     }, {
    //         id: 25,
    //         products: "RAJASTHAN ROYALS - TOTE BAGS PACK OF - 1",
    //         thumbnail: "https://res.cloudinary.com/dbe8yf165/image/upload/v1685796121/cricify/fan-merchandise/Rajasthan_Royals_-_Tote_Bags_Pack_of_-_1_-239_iliqat.jpg",
    //         Men: "yes",
    //         Women: "yes",
    //         Ipl: "yes",
    //         Wpl: "yes",
    //         International: "yes",
    //         Size: "One Size-Free Size",
    //         Category: "merchandise",
    //         Rating: "1.9",
    //         discountprice: 259,
    //         mrp: 459,
    //     },
    //     {
    //         id: 25,
    //         products: "KOLKATA KNIGHT RIDERS(KKR) JERSEY",
    //         thumbnail: "https://res.cloudinary.com/dbe8yf165/image/upload/v1685796158/cricify/ipl/kkr-match-jersey-2023-1304-back-front_fblla1.jpg",
    //         Men: "yes",
    //         Women: "no",
    //         Ipl: "yes",
    //         Wpl: "no",
    //         International: "no",
    //         Size: "One Size-Free Size",
    //         Category: "Jersey",
    //         Rating: "1.9",
    //         discountprice: 1259,
    //         mrp: 1459,
    //     }, {
    //         id: 26,
    //         products: "LUCKNOW SUPER GIANTS(LSG) JERSEY",
    //         thumbnail: "https://res.cloudinary.com/dbe8yf165/image/upload/v1685796159/cricify/ipl/lsg-match-jersey-2023-rahul-899-back-front_ounxgx.jpg",
    //         Men: "yes",
    //         Women: "no",
    //         Ipl: "yes",
    //         Wpl: "yes",
    //         International: "yes",
    //         Size: "One Size-Free Size",
    //         Category: "Jersey",
    //         Rating: "1.9",
    //         discountprice: 259,
    //         mrp: 459,
    //     }, {
    //         id: 27,
    //         products: "CHENNAI SUPER KINGS - THALA 7 CERAMIC MUG",
    //         thumbnail: "https://res.cloudinary.com/dbe8yf165/image/upload/v1685796121/cricify/fan-merchandise/Chennai_Super_Kings_-_Thala_7_Ceramic_Mug-399_w3juus.jpg",
    //         Men: "yes",
    //         Women: "yes",
    //         Ipl: "yes",
    //         Wpl: "no",
    //         International: "no",
    //         Size: "One Size-Free Size",
    //         Category: "Merchandise",
    //         Rating: "1.9",
    //         discountprice: 339,
    //         mrp: 499,
    //     },
    //     {
    //         id: 28,
    //         products: "MUMBAI INDIANS(MI) JERSEY",
    //         thumbnail: "https://res.cloudinary.com/dbe8yf165/image/upload/v1685796160/cricify/ipl/mi-match-jersey-2023-rohit-1099-back-front_lxiqid.jpg",
    //         Men: "yes",
    //         Women: "no",
    //         Ipl: "yes",
    //         Wpl: "no",
    //         International: "no",
    //         Size: "One Size-Free Size",
    //         Category: "Jersey",
    //         Rating: "1.9",
    //         discountprice: 1599,
    //         mrp: 1899,
    //     }, {
    //         id: 29,
    //         products: "SG OPTIPRO CRICKET HELMET",
    //         thumbnail: "https://res.cloudinary.com/dbe8yf165/image/upload/v1685796137/cricify/accessories/SG_Optipro_Cricket_Helmet-2005_pxjprt.jpg",
    //         Men: "yes",
    //         Women: "yes",
    //         Ipl: "no",
    //         Wpl: "no",
    //         International: "no",
    //         Size: "One Size-Free Size",
    //         Category: "Gears",
    //         Rating: "4.5",
    //         discountprice: 499,
    //         mrp: 999,
    //     }, {
    //         id: 30,
    //         products: "KOOKABURRA ADULT CRICKET BAT KB KAHUNA 1000",
    //         thumbnail: "https://res.cloudinary.com/dbe8yf165/image/upload/v1685796136/cricify/accessories/KOOKABURRA_Adult_Cricket_Bat_KB_Kahuna_1000-41142_dejeaj.jpg",
    //         Men: "yes",
    //         Women: "yes",
    //         Ipl: "yes",
    //         Wpl: "yes",
    //         International: "yes",
    //         Size: "One Size-Free Size",
    //         Category: "Gears",
    //         Rating: "1.9",
    //         discountprice: 33999,
    //         mrp: 39999,
    //     },
    //     {
    //         id: 31,
    //         products: "SG TEST LEATHER CRICKET BALL RED",
    //         thumbnail: "https://res.cloudinary.com/dbe8yf165/image/upload/v1685796137/cricify/accessories/SG_test_cricket_leather_ball-red-1799_m1q2w3.jpg",
    //         Men: "yes",
    //         Women: "yes",
    //         Ipl: "yes",
    //         Wpl: "yes",
    //         International: "yes",
    //         Size: "One Size-Free Size",
    //         Category: "Gears",
    //         Rating: "4.2",
    //         discountprice: 3499,
    //         mrp: 3599,
    //     }, {
    //         id: 32,
    //         products: "GUJARAT GIANTS(GG) WOMEN JERSEY",
    //         thumbnail: "https://res.cloudinary.com/dbe8yf165/image/upload/v1685796147/cricify/wpl/gg-women-match-jersey-2023-999-front_sfprmj.jpg",
    //         Men: "no",
    //         Women: "yes",
    //         Ipl: "yes",
    //         Wpl: "no",
    //         International: "no",
    //         Size: "One Size-Free Size",
    //         Category: "Merchandise",
    //         Rating: "1.9",
    //         discountprice: 33999,
    //         mrp: 39999,
    //     },
    //     {
    //         id: 33,
    //         products: "Royal Challengers Bangalore 2023 Women's Replica Jersey",
    //         thumbnail: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_600,h_600/global/606407/01/fnd/IND/fmt/png/Royal-Challengers-Bangalore-2023-Women's-Replica-Jersey",
    //         Men: "no",
    //         Women: "yes",
    //         Ipl: "yes",
    //         Wpl: "yes",
    //         International: "no",
    //         Size: "One Size-Free Size",
    //         Category: "Jersey",
    //         Rating: "5.0",
    //         discountprice: 1799,
    //         mrp: 1999,
    //     },



    // ]
    return (


        <NoteContext.Provider value={{ data: datas, function: setdata, userdata: userdata }}>
            {props.children}
        </NoteContext.Provider>
    )
}
export default NoteState;
